---
- name: installing nodejs USE ONLY ONCE
  hosts: debhosts
  become: true
  become_flags: -i
  become_user: nodejs

  tasks:

#  - name: adding user
#    user:
#      name: nodejs
#      shell: /bin/bash
#      password: "{{'87356' | password_hash('sha512', 'idinaxyidaiparol') }}"
#      create_home: yes
#      state: present

  - name: Install nvm
    ansible.builtin.shell: >
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    args:
      creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

  - name: Setup .profile
    ansible.builtin.lineinfile:
      path: ~/.profile
      line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
      create: yes

  - name: Install node
    ansible.builtin.shell: >
      nvm install 20.0
    args:
      executable: /bin/bash
      chdir: "$HOME"
      creates: "$HOME/.nvm/versions/node/v20.0"
